/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/*
* 游戏初始化配置;
*/
export class GameConfig {
    static width: number = 1280;
    static height: number = 720;
    static scaleMode: string = "fixedheight";
    static screenMode: string = "horizontal";
    static alignV: string = "top";
    static alignH: string = "left";
    static startScene: any = null;
    static sceneRoot: string = "";
    static debug: boolean = false;
    static stat: boolean = false;
    static physicsDebug: boolean = false;
    static exportSceneToJson: boolean = true;
    /**使用对象池方式 */
    static spineCache:boolean = true;
    constructor() { }
    static init() {
        var reg: Function = Laya.ClassUtils.regClass;

    }
}

GameConfig.init();